source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Forecasting' do
    use_frameworks!
    pod 'Alamofire'
    pod 'RxCoreLocation'
    pod 'Swinject'
    pod 'SwinjectStoryboard'
end